In [94]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np
import time
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score 
from sklearn.svm import SVC,LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier

In [95]:
df =  pd.read_csv('Data.csv')
df = df.set_index('id')
df = df.iloc[:,:-1]
y = df.loc[:,['diagnosis']]
x = df.iloc[:,1:]
output_dict = {'M':1,'B':0}
print(y.head())

         diagnosis
id                
842302           M
842517           M
84300903         M
84348301         M
84358402         M


In [96]:
y['diagnosis'] = y['diagnosis'].map(lambda x : output_dict.get(x))
print(y[:10])

          diagnosis
id                 
842302            1
842517            1
84300903          1
84348301          1
84358402          1
843786            1
844359            1
84458202          1
844981            1
84501001          1


In [97]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2, random_state = 42)
print(xtrain.shape)
print(ytrain.head())
accuracies  = [] # list to store accuracy for n number of algorithms 
cvs = [] # cross-validartion score 
cost = [] # time is the measure of cost in this case

(455, 30)
          diagnosis
id                 
859471            0
873593            1
859196            0
88466802          0
858970            0


In [102]:
model_algorithms=[LogisticRegression(),SVC(),LinearSVC(),DecisionTreeRegressor(),RandomForestClassifier(n_estimators=12),KNeighborsClassifier(n_neighbors=6)]

In [99]:
for clf in model_algorithms:
    start_time = time.time()
    clf.fit(xtrain,ytrain)
    p = clf.predict(xtest)
    stop_time = time.time()
    print(p[:10])
    print(ytest[:10])
    prediction_vs_correct = pd.DataFrame({'P':p,'R':ytest.diagnosis})
    print(prediction_vs_correct[:10])
    time_taken = start_time - stop_time
    cost.append(time_taken)
    current_accuracy = accuracy_score(p,ytest.diagnosis)
    accuracies.append(current_accuracy)
    print("Current Accuracy:")
    print(current_accuracy)
    # cv = 5 -> Repeat the experiment 5 times
    current_cvs = cross_val_score(clf,x,y,cv=5)
    print(current_cvs)
    cvs.append(np.mean(current_cvs))
    print(cvs)

[0 1 1 0 0 1 1 1 0 0]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
         P  R
id           
87930    0  0
859575   1  1
8670     1  1
907915   0  0
921385   0  0
927241   1  1
9012000  1  1
853201   1  1
8611161  0  0
911673   0  0
Current Accuracy:
0.956140350877193
[0.93043478 0.93913043 0.97345133 0.94690265 0.96460177]
[0.9509041939207385]
[0 0 0 0 0 0 0 0 0 0]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
         P  R
id           
87930    0  0
859575   0  1
8670     0  1
907915   0  0
921385   0  0
927241   0  1
9012000  0  1
853201   0  1
8611161  0  0
911673   0  0
Current Accuracy:
0.6228070175438597


C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, )

[0.62608696 0.62608696 0.62831858 0.62831858 0.62831858]
[0.9509041939207385, 0.6274259330511736]
[0 1 1 0 0 1 1 0 0 0]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
         P  R
id           
87930    0  0
859575   1  1
8670     1  1
907915   0  0
921385   0  0
927241   1  1
9012000  1  1
853201   0  1
8611161  0  0
911673   0  0
Current Accuracy:
0.9035087719298246
[0.90434783 0.93043478 0.92920354 0.94690265 0.88495575]
[0.9509041939207385, 0.6274259330511736, 0.9191689111196613]
[0. 1. 1. 0. 0. 1. 1. 1. 1. 0.]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
           P  R
id             
87930    0.0  0
859575   1.0  1
8670 

C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\rangan_basu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py

[0.45332481 0.71365777 0.73040541 0.67626775 0.15075155]
[0.9509041939207385, 0.6274259330511736, 0.9191689111196613, 0.54488145603443]
[0 1 1 0 0 1 1 1 0 0]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
         P  R
id           
87930    0  0
859575   1  1
8670     1  1
907915   0  0
921385   0  0
927241   1  1
9012000  1  1
853201   1  1
8611161  0  0
911673   0  0
Current Accuracy:
0.9736842105263158
[0.95652174 0.94782609 0.97345133 0.97345133 0.97345133]
[0.9509041939207385, 0.6274259330511736, 0.9191689111196613, 0.54488145603443, 0.9649403616775685]
[0 1 1 0 0 1 1 1 0 0]
         diagnosis
id                
87930            0
859575           1
8670             1
907915           0
921385           0
927241           1
9012000          1
853201           1
8611161          0
911673           0
   

In [ ]:
# Random Forests Give the best Accuracy For Cancer Prediction with accuracy = 97%